school-managemnet/Controllers/DepartmentController.cs
using SchoolManagement.BLL;
using SchoolManagement.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace SchoolManagement.Controllers
{
    //[Authorize]
    public class DepartmentController : Controller
    {
        private readonly IDepartment _db;

        public DepartmentController(IDepartment db)
        {
            this._db = db;
        }


        public IActionResult Details(Department department)
        {
            Department dept = _db.GetById(department.Id);
            return View(dept);
        }

        [HttpPost]
        public IActionResult Create(Department department)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            if (ModelState.IsValid)
            {
                _db.Add(department);
                return RedirectToAction("Index");
            }

            return View();

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Department department)
        {

            if (ModelState.IsValid)
            {
                _db.Edit(department);
                return RedirectToAction("Details", department);
            }

            return View(department);

        }
        public IActionResult Edit(int id)
        {
            return View(_db.GetById(id));
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var model = _db.GetAll();
            return View(model);
        }


        [HttpPost]
        public IActionResult Delete(Department department)
        {
            _db.Delete(department.Id);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {

            return View(_db.GetById(id.Value));
        }

    }
}

school-managemnet/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SchoolManagement.ViewModels;

namespace SchoolManagement.Controllers
{
    [Authorize(Roles = "Admin")] // [Authorize(Roles = "Admin,Student")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager) 
        {
            this._roleManager = roleManager;
        }

        // Create Role
        // Link
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }

        // Submit
        [HttpPost]
        public async Task<IActionResult> New(RoleViewModel newRoleVm)
        {
            if(ModelState.IsValid)
            {
                IdentityRole role = new();
                role.Name = newRoleVm.RoleName;
                IdentityResult result = await _roleManager.CreateAsync(role);
                if(result.Succeeded)
                {
                    return View(new RoleViewModel());
                }
                foreach(var item in result.Errors)
                {
                    ModelState.AddModelError("",item.Description);
                }
            }
           
            return View(newRoleVm);
        }
    }
}

school-managemnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contoso University</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContosoUniversity.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Contoso University</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Courses/Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Instructors/Index">Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        
                       @if (User.IsInRole("Admin"))
                                           {
                                                 <li class="nav-item">
                                                   <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="New">Role</a>
                                               </li>
                                                <li class="nav-item">
                                                   <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="AddAdmin">Add Admin</a>
                                               </li>
                                           }
                                         
                                          
                                           </ul>
                   
                                       <ul class="navbar-nav">
                                           @if (User.Identity.IsAuthenticated)
                                           {
                                               <li class="nav-item">
                                                  Welcome, @User.Identity.Name
                                               </li>
                                               <li class="nav-item">
                                                   <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                               </li>
                                           }
                                           else
                                           {
                                               <li class="nav-item">
                                                   <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                               </li>
                   
                                               <li class="nav-item">
                                                   <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                               </li>
                                           }
                                       
                                          @*  <li class="nav-item">
                                               <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">Profile</a>
                                           </li> *@
                                       </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Contoso University - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>